language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.1
  - 7.2
  - nightly

sudo: false

services:
  - mysql

before_script:
  - mysql -u root -e 'create database laravelUsers;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - composer create-project --prefer-dist laravel/laravel laravelusers
  - cp .env.travis laravelusers/.env
  - cd laravelusers
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer require jeremykenedy/laravel-users
  - php artisan key:generate
  - php artisan vendor:publish --tag=laravelusers
  - php artisan make:auth
  - composer dump-autoload
  - php artisan clear-compiled
